# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 409fa7e4715846e05b6b797e61c9ecb4039b1a285180b3dc6dfa6403bb21dfc8c9bd5957ef52cf192411a768acf88134f1549f30a857e8d9c6e6f87724653464

test:
  secret_key_base: cb5893818f02c41fdab8a8d2904e0273d83be47f3f18680b1e4dae19fb2e481981c475cd0b623b40773d8093f9221703dcef0c5c69995478c169d46ccab07394

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
